### PR TITLE
Separate messaging resources into separate module

### PR DESCRIPTION
**Pull request by kuujo**
This PR separates the `DistributedMessageBus`, `DistributedTopic`, and `DistributedTaskQueue` into a separate `atomix-messaging` module. Pretty self-explanitory :-)

### CODE REVIEW

**Comment by electrical** [comment]
Failures: `java.lang.IllegalArgumentException: a type with the ID -25 already exists`

**Comment by electrical** [comment]
Think it comes from https://github.com/atomix/atomix/pull/90/files#diff-d5e88c1ac75a1b81c4499dbe61526002R37 ?

**Comment by jhalterman** [comment]
Yep - DistributedTaskQueue and DistributedTopic share the same ResourceTypeInfo id.

**Comment by kuujo** [comment]
Should be fixed. Will merge after the tests pass.

**Comment by electrical** [comment]
Build stalled due to testing bug. Is there a way to retrigger the run?

**Comment by kuujo** [comment]
Merging this PR with failing tests that should be largely fixed by a follow up PR for the client.

**Pull request merged**
