### PR TITLE
Fix VERSION resource conflicts.

### PR DESCRIPTION
**Pull request by ynfeng**
Ref to #1058

### CODE REVIEW

**Comment by johnou** [comment]
Personally I think it's nicer if we move it to a package instead eg. io/atomix/VERSION

**Comment by johnou** [comment]
@ynfeng please move the file to the new path as per my review.

**Comment by ynfeng** [comment]
> @ynfeng please move the file to the new path as per my review.

ok

**Comment by ynfeng** [comment]
@johnou done

**Comment by ynfeng** [comment]
@johnou done.

**Review by johnou — APPROVED** [review]

**Pull request merged**
