### PR TITLE
Handle tomestones in cluster metadata service.

### PR DESCRIPTION
**Pull request by johnou**
Fixes https://github.com/atomix/atomix/issues/375

### CODE REVIEW

**Comment by kuujo** [comment]
The problem here is the tombstones _need_ to be retained in the map so they can be replicated, otherwise other nodes will not learn about deleted nodes. If a node is simply removed from the map then that change will never be replicated. Tombstones need to be retained until some arbitrary point in the future to ensure deletes are replicated to all nodes. [This condition](https://github.com/johnou/atomix/blob/5831f7d2f7534a565d7d74bea62e80f034e432a5/cluster/src/main/java/io/atomix/cluster/impl/DefaultClusterMetadataService.java#L264-L265) is supposed to stop anti-entropy advertisements from being sent to removed nodes, and we need to figure out why that's not preventing anti-entropy advertisements from being sent to deleted nodes.

**Comment by kuujo** [comment]
We should probably write a test for this and work back from there

**Comment by johnou** [comment]
@kuujo couldn't we just revert everything except the changes to pickRandomPeer

**Comment by johnou** [comment]
@kuujo PTAL

**Comment by kuujo** [comment]
Yep that should work

**Pull request merged**
