### PR TITLE
Member's metadata

### LINKED ISSUE #529: Member's metadata
In atomix v1, a member had an option to associate some meta-data when joining a cluster, now I see that a member has tags but it is less flexible that meta-data, would it possible to switch from tags to meta-data or have a way to add arbitrary meta-data to a member when joining a cluster ?

### PR DESCRIPTION
**Pull request by lburgazzoli**
Fixes #529

### CODE REVIEW

**Comment by johnou** [comment]
@lburgazzoli simple unit test to show it replicates?

**Comment by lburgazzoli** [comment]
@johnou can you point me to a simple test doing something similar ?

**Comment by johnou** [comment]
@lburgazzoli something like io.atomix.core.AtomixTest#testClientJoinLeavePersistent but checking tags are the same between nodes instead of events, remember it's a hashmap so order is not deterministic.

**Comment by lburgazzoli** [comment]
done

**Comment by johnou** [comment]
@lburgazzoli thanks! :rocket:

**Pull request merged**
