### PR TITLE
Fix memory leak in Raft member selectors on branch 3.0

### PR DESCRIPTION
**Pull request by sndaergg**

### CODE REVIEW

**Comment by sndaergg** [comment]
We are using atomix 3.11 and I want merge this fix into branch 3.0, Is CI unstable or something wrong?

**Comment by johnou** [comment]
@sndaergg Travis removed one of the Oracle jdks, I updated the CI configuration.

**Comment by sndaergg** [comment]
> @sndaergg Travis removed one of the Oracle jdks, I updated the CI configuration.

Thanks johnou!
But CI failed again, can I retrigger it?

**Comment by sndaergg** [comment]
CI passed， and no merge button?

**Comment by sndaergg** [comment]
I also need new 3.0.X release base on this PR,Thanks

**Comment by skyfirst93** [comment]
Is their any update when the release for 3.0.x  with this fix come

**Comment by sndaergg** [comment]
I need a new 3.0 release with this fix, help me please! @johnou

**Comment by johnou** [comment]
@sndaergg only kuujo can cut new releases.

**Comment by sndaergg** [comment]
> @sndaergg only kuujo can cut new releases.

And what can I do now？any suggestion?

**Pull request closed without merging**
