### PR TITLE
Implement DistributedSemaphore.

### PR DESCRIPTION
**Pull request by tanbangcheng**
```JAVA
DistributedSemaphore semaphore = atomix.semaphoreBuilder("test-semaphore-blocking")
		.withInitialCapacity(10)
		.build();

semaphore.acquire();

try {
  //do something
} finally {
  semaphore.release();
}
```

### CODE REVIEW

**Comment by kuujo** [comment]
This is awesome!

Unfortunately, with the final 2.1 API changes we need to rebase this PR and fix merge conflicts. The most relevant changes are:

* All primitives are partitioned, and single partition primitive like this one can use a partition key via `getPartitionKey()`

* Primitive implementations have simpler methods for interacting with their service:
  * `invokeOn(PartitionId partitionId, ...)` invokes an operation on a specific partition
  * `invokeBy(String key, ...)` invokes an operation on the owning partition for the given key
  * `invokeAll(...)` invokes an operation on all partitions in the group

For this primitive, we’ll just have to use `invokeBy(getPartitionKey(), ...)` for all operations.

I don’t mind doing these changes myself, but I want to be careful to ensure you still get credit for authoring this primitive.

**Comment by kuujo** [comment]
I actually meant to merge this before I merged #528. That probably broke the API again, but it adds a feature that's specifically intended for this type of primitive: the ability to configure the primitive service. You can just implement it like the others are currently implemented (add `ServiceConfig` to the `PrimitiveType` generic parameters) and I will add the custom configuration, or you can figure that out yourself. Up to you.

**Comment by kuujo** [comment]
I was gonna mess with this and get it merged, but I'll let you do it.

**Comment by johnou** [comment]
@tanbangcheng ping :)

**Comment by kuujo** [comment]
I can do this if we have commit access to the branch on the fork.

**Comment by tanbangcheng** [comment]
@kuujo done, but proxy config is same as service config, is there a better way?

**Comment by tanbangcheng** [comment]
@johnou pong :)

**Comment by kuujo** [comment]
I think this looks good.

Yeah, good point. Adding verbs directly to the primitive resources with no path doesn't work. This is just left over from the REST API refactoring. Need to go through all the REST resources and test them again.

**Pull request merged**
