### PR TITLE
Refactoring to make Atomix OSGi compliant

### PR DESCRIPTION
**Pull request by madjam**
Follow up to https://github.com/atomix/catalyst/pull/49 and https://github.com/atomix/copycat/pull/224
Apart from the expected package name updates, there are few changes to deal with split packaging. Couple other package location changes were made to ensure externally usable classes do not reside inside a *internal package (as these do not get exported by maven bundle plugin by default)

### CODE REVIEW

**Comment by jhalterman** [comment]
So what's the general rationale for the packaging moves, like `io.atomix.catalyst.util.concurrent.Scheduled` to `io.atomix.catalyst.concurrent.Scheduled` and `io.atomix.catalyst.transport.NettyTransport` to `io.atomix.catalyst.transport.netty.NettyTransport`?

**Comment by kuujo** [comment]
I also am curious about that since I'm quite ignorant of all the complexities of OSGi.

**Comment by madjam** [comment]
Multiple bundles exporting same package is highly discouraged in OSGi. In Catalyst, `io.atomix.catalyst.transport` and `io.atomix.catalyst.util` packages exist in (i.e. are split across) multiple bundles. The renaming for `io.atomix.catalyst.transport` in `catalyst-netty` to `io.atomix.catalyst.transport.netty` and similar change in `catalyst-local` is an attempt to address this split package problem.

**Comment by jhalterman** [comment]
@madjam Cool - makes sense.

**Comment by kuujo** [comment]
Rerunning tests with atomix/copycat#224 merged...

**Pull request merged**
