### PR TITLE
Generate HTML5 javadocs

### PR DESCRIPTION
**Pull request by johnou**

### CODE REVIEW

**Comment by kuujo** [comment]
Just need to verify it still works with the website stylesheet

**Comment by johnou** [comment]
screencapture-localhost-8080-overview-summary-html-2018-07-21-23_17_54

**Comment by johnou** [comment]
http://hg.openjdk.java.net/jdk/jdk/file/7a7285477153/src/jdk.javadoc/share/classes/jdk/javadoc/internal/doclets/toolkit/resources/stylesheet.css

**Comment by johnou** [comment]
I still need to integrate the new styles.

**Comment by johnou** [comment]
Took the latest openjdk stylesheet then tried to keep existing styling, replaced pngs with base64 for improved portability.

**Pull request merged**
