### PR TITLE
fix(protocols/raft): apply raft partition group configuration

### PR DESCRIPTION
**Pull request by saig0**
Apply raft configuration instead of using hardcoded values for election timeout, heartbeat interval and session timeout.

### CODE REVIEW

**Comment by johnou** [comment]
@saig0 are the defaults in the builder the same?

**Comment by saig0** [comment]
Yes, the defaults are the same.

**Comment by johnou** [comment]
@saig0 thanks!

**Comment by marcinostry** [comment]
hello @johnou @saig0 
Do you know when tagged version contains the fix will be released? I can see the latest tagged version is 3.1.5. Should I expect 3.1.6 in near future?

**Pull request merged**
